FROM ubuntu
MAINTAINER Dean Efrati <deanefrati@gmail.com>

WORKDIR /tmp

RUN apt-get -y install software-properties-common apache2 unzip && apt-get clean
ADD Apache-v2.2-Linux-64-Agent-3.3.3.zip /tmp/openam-web-agent.zip

RUN add-apt-repository ppa:webupd8team/java \
	&& apt-get update \
	&& echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections \
	&& apt-get install -y oracle-java8-installer

RUN echo password > pwd.txt \
	&& chmod 400 pwd.txt \
	&& ln -s /etc/apache2/apache2.conf /etc/apache2/httpd.conf \
	&& unzip openam-web-agent.zip

EXPOSE 80
#CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
